#!/opt/third-party/bin/perl -w

use strict;
use Getopt::Long;
use Time::ParseDate;
use Date::Format;
use Data::Dumper;
$Data::Dumper::Indent = 1;

my $VERSION = "1.0.0";

my %option;
GetOptions(\%option,
	   'config=s',
	   'debug',
	   'help',
	   'log',
	   'save=s',
	   'small',
	   'title=s',
	   'view',
	  );

if ($option{help}) {
  &usage;
  exit;
}

$option{config} = glob('~') . '/.zengraphrc'
  unless ($option{config});

unless (-f $option{config}) {
  print "Need a --config or ~/.zengraphrc must exist\n\n";
  &usage;
  exit(1);
}

$option{save} = ''
  unless $option{save};
$option{title} = ''
  unless $option{title};
$option{title} .= ($option{title} ? ' \n' : '') . "Generated: " . localtime;

my $date = '';
my $data = {};
my $first_date = 0;

my $config = `cat $option{config}`;
print "$config\n\n" if $option{debug};
eval $config;
die "Error in eval: $@" if $@;

foreach my $file (@ARGV) {
  open IN, $file || die "Couldn't open file '$file': $!";

  &process_file($file);
  while (<IN>) {
    &process_line($_);
  }
}

my @titles = ();
foreach my $date (sort {$a cmp $b} keys %{$data}) {
  foreach my $key (sort keys %{$data->{$date}}) {
    unless (grep $_ eq $key, @titles) {
      unshift @titles, $key;
    }
  }
}

@titles = sort @titles;

print Dumper(\@titles) if $option{debug};
print Dumper($data) if $option{debug};

open OUT, ">temp.$$.dat" || die "temp.$$.dat: $!";
foreach ('#Day', @titles) {
  printf OUT "%8s ", $_;
}
print OUT "\n";

foreach my $date (sort {$a cmp $b} keys %{$data}) {

  my $record = $data->{$date};

  printf OUT "%s ", $date;
  foreach my $tag (@titles) {
    printf OUT "%8d ", $record->{$tag} || 0;
  }
  print OUT "\n";
}
close OUT;

open OUT, ">temp.$$.dem" || die "temp.$$.dem: $!";
print OUT "set terminal png small color\n";
print OUT "set output 'temp.$$.png'\n";
print OUT "set timefmt '%Y-%m-%d'\n";
print OUT "set xdata time\n";
print OUT "set logscale y\n" if $option{log};
print OUT "set ylabel 'Count'\n";
print OUT "set xlabel 'Date'\n";
print OUT "set title \"$option{title}\"\n";

if ($option{small}) {
  print OUT "set size .5,.5\n";
  print OUT "set xtics rotate\n";
  print OUT "set format x \"%m-%d\"\n";
} else {
  print OUT "set format x \"%m-%d\\n%Y\"\n";
}


print OUT "plot ";

# 1 red
# 2 lime green
# 3 blue
# 4 cyan
# 5 magenta
# 6 yellow
# 7 brownish
# 8 forest green
# 9 navy blue (may be just blue)
# repeat

# I can't stand cyan or yellow on a white background
my @lt = qw( 1 2 3 5 7 8 9 );
@lt = (@lt, @lt, @lt, @lt, @lt);

my $i = 1;
foreach my $title (@titles) {
  print OUT ", " if $i++ > 1;
  print OUT "'temp.$$.dat' using 1:$i t '$title' with lines lt $lt[$i]";
}
print OUT "\n";
close OUT;

`/usr/local/bin/gnuplot temp.$$.dem`;

`cp temp.$$.png $option{save}`
  if $option{save};

`xv temp.$$.png`
  if $option{view};

unlink "temp.$$.dem", "temp.$$.dat", "temp.$$.png";

############################################################
# Subroutines:

sub usage {
  my $prog = $0;
  $prog =~ s|^[^/]*||;

  print "Usage: $prog [options] files\n";
  print "  --config <file> - Use <file> for configuration. Default ~/.zengraphrc.\n";
  print "  --save <file>   - Saves the graph in <file>.\n";
  print "  --help          - Display this usage.\n";
  print "  --title <title> - Name the graph <title>.\n";
  print "  --view          - View the graph in xv.\n";
}
